=== internetofwater/geoconnex.us/pygeoapi/schemas.opengis.net/tms/1.0/json/tms-schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "",
	"description": "",
	"type": "object",
	"required": ["type", "identifier", "supportedCRS", "tileMatrix"],
	"properties": {
		"type": {
			"description": "Type of the Tile Matrix Set",
			"enum": ["TileMatrixSetType"]
		},
		"title": {
			"description": "Title of this tile matrix set, normally used for display to a human",
			"type": "string"
		},
		"abstract": {
			"description": "Brief narrative description of this tile matrix set, normally available for display to a human",
			"type": "string"
		},
		"keywords": {
			"description": "Unordered list of one or more commonly used or formalized word(s) or phrase(s) used to describe this dataset",
			"$ref": "#/definitions/keywords" 
		},
		"identifier": {
			"description": "Tile matrix set identifier",
			"type": "string"
		},
		"boundingBox":
		{
			"description": "Minimum bounding rectangle surrounding the tile matrix set, in the supported CRS",
			"$ref": "#/definitions/boundingBox" 
		},
		"supportedCRS": {
			"description": "Reference to one coordinate reference system (CRS)",
			"type": "string",
			"format": "uri"
		},
		"wellKnownScaleSet": {
			"description": "Reference to a well-known scale set",
			"type": "string",
			"format": "uri"
		},
		"tileMatrix":
		{
			"description": "Describes a scale level and its tile matrix",
			"$ref": "#/definitions/tileMatrix" 
		}
	},
	"definitions":{ 
		"keywords": {
			"description": "Unordered list of one or more commonly used or formalised word(s) or phrase(s) used to describe this resource",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"boundingBox": {
			"description": "Minimum bounding rectangle surrounding the tile matrix set, in the supported CRS",
			"type": "object",
			"required": ["type", "lowerCorner", "upperCorner"],
			"properties": 
			{
				"type": {
					"description": "Type of the Bounding Bos",
					"enum": ["BoundingBoxType"]
				},
				"crs": {
					"description": "",
					"type": "string",
					"format": "uri"
				},
				"lowerCorner": {					
					"description": "",
					"type": "array",
					"items": {
						"type": "number",
						"minItems": 2,
						"maxItems": 2
					}
				},
				"upperCorner": {					
					"description": "",
					"type": "array",
					"items": {
						"type": "number",
						"minItems": 2,
						"maxItems": 2
					}
				}
			}
		},
		"tileMatrix": 
		{
			"description": "",
			"type": "array",
			"items": {
				"description": "",
				"type": "object",
				"required": ["type", "identifier", "scaleDenominator", "topLeftCorner", "tileWidth", "tileHeight", "matrixWidth", "matrixHeight"],
				"properties": 
				{
					"type": {
						"description": "Type of the Tile Matrix",
						"enum": ["TileMatrixType"]
					},
					"title": {
						"description": "Title of this tile matrix set, normally used for display to a human",
						"type": "string"
					},
					"abstract": {
						"description": "Brief narrative description of this tile matrix set, normally available for display to a human",
						"type": "string"
					},
					"keywords": {
						"description": "Unordered list of one or more commonly used or formalized word(s) or phrase(s) used to describe this dataset",
						"$ref": "#/definitions/keywords" 
					},
					"identifier": {
						"description": "Tile matrix identifier",
						"type": "string"
					},
					"scaleDenominator": {
						"description": "Scale denominator level of this tile matrix",
						"type": "number"
					},
					"topLeftCorner": {					
						"description": "Position in CRS coordinates of the top-left corner of this tile matrix",
						"type": "array",
						"items": {
							"type": "number",
							"minItems": 2,
							"maxItems": 2
						}
					},
					"tileWidth": {
						"description": "Width of each tile of this tile matrix in pixels",
						"type": "number",
						"minimum": 1,
						"multipleOf" : 1
					},
					"tileHeight": {
						"description": "Height of each tile of this tile matrix in pixels",
						"type": "number",
						"minimum": 1,
						"multipleOf" : 1
					},
					"matrixWidth": {
						"description": "Width of the matrix (number of tiles in width)",
						"type": "number",
						"minimum": 1,
						"multipleOf" : 1
					},
					"matrixHeight": {
						"description": "Height of the matrix (number of tiles in height)",
						"type": "number",
						"minimum": 1,
						"multipleOf" : 1
					},
					"variableMatrixWidth": {
						"description": "Describes the rows that has variable matix width",
						"$ref": "#/definitions/variableMatrixWidth" 
					}
				}
			}
		},
		"variableMatrixWidth": {
			"description": "List of data structures defining the tiles rows that was variable width",
			"type": "array",
			"items": {
				"description": "Variable Matrix Width data structure",
				"type": "object",
				"required": ["type", "coalesce", "minTileRow", "maxTileRow"],
				"properties": 
				{
					"type": {
						"description": "Type of the Variable Matrix Width",
						"enum": ["VariableMatrixWidthType"]
					},
					"coalesce" : {
						"description": "Coalescence factor",
						"type": "number",
						"minimum": 2,
						"multipleOf" : 1
					},
					"minTileRow": {
						"description": "Minimum tile row index valid for this layer",
						"type": "number",
						"minimum": 0,
						"multipleOf" : 1
					},
					"maxTileRow": {
						"description": "Maximim tile row index valid for this layer",
						"type": "number",
						"minimum": 0,
						"multipleOf" : 1
					}
				}
			}
		}
	}
}

=== internetofwater/geoconnex.us/pygeoapi/schemas.opengis.net/tms/1.0/json/examples/CanadianNAD83_LCC.json
{
	"type": "TileMatrixSetType",
	"title": "Lambert conformal conic NAD83 for Canada",
	"identifier": "CanadianNAD83_LCC ",
	"boundingBox":
	{
		"type": "BoundingBoxType",
		"crs": "http://www.opengis.net/def/crs/EPSG/0/3978",
		"lowerCorner":
		[
			-7786476.885838887,
			-5153821.09213678
		],
		"upperCorner":
		[
			7148753.233541353,
			7928343.534071138
		]
	},
	"supportedCRS": "http://www.opengis.net/def/crs/EPSG/0/3978",
	"tileMatrix":
	[
		{
			"type": "TileMatrixType",
			"identifier": "0",
			"scaleDenominator": 145000000,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 5,
			"matrixHeight": 5
		},
		{
			"type": "TileMatrixType",
			"identifier": "1",
			"scaleDenominator": 85000000,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 8,
			"matrixHeight": 8
		},
		{
			"type": "TileMatrixType",
			"identifier": "2",
			"scaleDenominator": 50000000,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 13,
			"matrixHeight": 14
		},
		{
			"type": "TileMatrixType",
			"identifier": "3",
			"scaleDenominator": 30000000,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 21,
			"matrixHeight": 22
		},
		{
			"type": "TileMatrixType",
			"identifier": "4",
			"scaleDenominator": 17500000,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 36,
			"matrixHeight": 38
		},
		{
			"type": "TileMatrixType",
			"identifier": "5",
			"scaleDenominator": 10000000,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 62,
			"matrixHeight": 66
		},
		{
			"type": "TileMatrixType",
			"identifier": "6",
			"scaleDenominator": 6000000,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 103,
			"matrixHeight": 110
		},
		{
			"type": "TileMatrixType",
			"identifier": "7",
			"scaleDenominator": 3500000,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 177,
			"matrixHeight": 188
		},
		{
			"type": "TileMatrixType",
			"identifier": "8",
			"scaleDenominator": 2000000,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 309,
			"matrixHeight": 329
		},
		{
			"type": "TileMatrixType",
			"identifier": "9",
			"scaleDenominator": 1200000,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 515,
			"matrixHeight": 548
		},
		{
			"type": "TileMatrixType",
			"identifier": "10",
			"scaleDenominator": 700000,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 882,
			"matrixHeight": 938
		},
		{
			"type": "TileMatrixType",
			"identifier": "11",
			"scaleDenominator": 420000,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 1470,
			"matrixHeight": 1563
		},
		{
			"type": "TileMatrixType",
			"identifier": "12",
			"scaleDenominator": 250000,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 2469,
			"matrixHeight": 2626
		},
		{
			"type": "TileMatrixType",
			"identifier": "13",
			"scaleDenominator": 145000,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 4257,
			"matrixHeight": 4528
		},
		{
			"type": "TileMatrixType",
			"identifier": "14",
			"scaleDenominator": 85000,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 7262,
			"matrixHeight": 7723
		},
		{
			"type": "TileMatrixType",
			"identifier": "15",
			"scaleDenominator": 50000,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 12344,
			"matrixHeight": 13130
		},
		{
			"type": "TileMatrixType",
			"identifier": "16",
			"scaleDenominator": 30000,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 20574,
			"matrixHeight": 21882
		},
		{
			"type": "TileMatrixType",
			"identifier": "17",
			"scaleDenominator": 17500,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 35269,
			"matrixHeight": 37512
		},
		{
			"type": "TileMatrixType",
			"identifier": "18",
			"scaleDenominator": 10000,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 61720,
			"matrixHeight": 65646
		},
		{
			"type": "TileMatrixType",
			"identifier": "19",
			"scaleDenominator": 6000,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 102866,
			"matrixHeight": 109409
		},
		{
			"type": "TileMatrixType",
			"identifier": "20",
			"scaleDenominator": 3500,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 176341,
			"matrixHeight": 187558
		},
		{
			"type": "TileMatrixType",
			"identifier": "21",
			"scaleDenominator": 2000,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 308596,
			"matrixHeight": 328227
		},
		{
			"type": "TileMatrixType",
			"identifier": "22",
			"scaleDenominator": 1200,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 514327,
			"matrixHeight": 547044
		},
		{
			"type": "TileMatrixType",
			"identifier": "23",
			"scaleDenominator": 700,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 881703,
			"matrixHeight": 937790
		},
		{
			"type": "TileMatrixType",
			"identifier": "24",
			"scaleDenominator": 420,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 1469505,
			"matrixHeight": 1562983
		},
		{
			"type": "TileMatrixType",
			"identifier": "25",
			"scaleDenominator": 250,
			"topLeftCorner":
			[
				-34655800,
				39310000
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 2468768,
			"matrixHeight": 2625811
		}
	]
}

=== internetofwater/geoconnex.us/pygeoapi/schemas.opengis.net/tms/1.0/json/examples/EuropeanETRS89_LAEAQuad.json
{
	"type": "TileMatrixSetType",
	"title": "Lambert Azimuthal Equal Area ETRS89 for Europe",
	"identifier": "EuropeanETRS89_LAEAQuad",
	"boundingBox":
	{
		"type": "BoundingBoxType",
		"crs": "http://www.opengis.net/def/crs/EPSG/0/3035",
		"lowerCorner":
		[
			2000000.0,
			1000000.0
		],
		"upperCorner":
		[
			6500000.0,
			5500000.0
		]
	},
	"supportedCRS": "http://www.opengis.net/def/crs/EPSG/0/3035",
	"tileMatrix":
	[
		{
			"type": "TileMatrixType",
			"identifier": "0",
			"scaleDenominator": 62779017.8571428,
			"topLeftCorner":
			[
				2000000.0,
				5500000.0
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 1,
			"matrixHeight": 1
		},
		{
			"type": "TileMatrixType",
			"identifier": "1",
			"scaleDenominator": 31389508.9285714,
			"topLeftCorner":
			[
				2000000.0,
				5500000.0
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 2,
			"matrixHeight": 2
		},
		{
			"type": "TileMatrixType",
			"identifier": "2",
			"scaleDenominator": 15694754.4642857,
			"topLeftCorner":
			[
				2000000.0,
				5500000.0
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 4,
			"matrixHeight": 4
		},
		{
			"type": "TileMatrixType",
			"identifier": "3",
			"scaleDenominator": 7847377.23214285,
			"topLeftCorner":
			[
				2000000.0,
				5500000.0
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 8,
			"matrixHeight": 8
		},
		{
			"type": "TileMatrixType",
			"identifier": "4",
			"scaleDenominator": 3923688.61607142,
			"topLeftCorner":
			[
				2000000.0,
				5500000.0
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 16,
			"matrixHeight": 16
		},
		{
			"type": "TileMatrixType",
			"identifier": "5",
			"scaleDenominator": 1961844.30803571,
			"topLeftCorner":
			[
				2000000.0,
				5500000.0
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 32,
			"matrixHeight": 32
		},
		{
			"type": "TileMatrixType",
			"identifier": "6",
			"scaleDenominator": 980922.154017857,
			"topLeftCorner":
			[
				2000000.0,
				5500000.0
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 64,
			"matrixHeight": 64
		},
		{
			"type": "TileMatrixType",
			"identifier": "7",
			"scaleDenominator": 490461.077008928,
			"topLeftCorner":
			[
				2000000.0,
				5500000.0
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 128,
			"matrixHeight": 128
		},
		{
			"type": "TileMatrixType",
			"identifier": "8",
			"scaleDenominator": 245230.538504464,
			"topLeftCorner":
			[
				2000000.0,
				5500000.0
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 256,
			"matrixHeight": 256
		},
		{
			"type": "TileMatrixType",
			"identifier": "9",
			"scaleDenominator": 122615.269252232,
			"topLeftCorner":
			[
				2000000.0,
				5500000.0
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 512,
			"matrixHeight": 512
		},
		{
			"type": "TileMatrixType",
			"identifier": "10",
			"scaleDenominator": 61307.634626116,
			"topLeftCorner":
			[
				2000000.0,
				5500000.0
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 1024,
			"matrixHeight": 1024
		},
		{
			"type": "TileMatrixType",
			"identifier": "11",
			"scaleDenominator": 30653.817313058,
			"topLeftCorner":
			[
				2000000.0,
				5500000.0
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 2048,
			"matrixHeight": 2048
		},
		{
			"type": "TileMatrixType",
			"identifier": "12",
			"scaleDenominator": 15326.908656529,
			"topLeftCorner":
			[
				2000000.0,
				5500000.0
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 4096,
			"matrixHeight": 4096
		},
		{
			"type": "TileMatrixType",
			"identifier": "13",
			"scaleDenominator": 7663.45432826451,
			"topLeftCorner":
			[
				2000000.0,
				5500000.0
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 8192,
			"matrixHeight": 8192
		},
		{
			"type": "TileMatrixType",
			"identifier": "14",
			"scaleDenominator": 3831.72716413225,
			"topLeftCorner":
			[
				2000000.0,
				5500000.0
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 16384,
			"matrixHeight": 16384
		},
		{
			"type": "TileMatrixType",
			"identifier": "15",
			"scaleDenominator": 1915.86358206612,
			"topLeftCorner":
			[
				2000000.0,
				5500000.0
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 32768,
			"matrixHeight": 32768
		}
	]
}

=== internetofwater/geoconnex.us/pygeoapi/schemas.opengis.net/tms/1.0/json/examples/UTM31WGS84Quad.json
{
	"type": "TileMatrixSetType",
	"title": "UTM31WGS84Quad",
	"identifier": "Universal Transverse Mercator Zone 31 WGS84 Quad",
	"boundingBox":
	{
		"type": "BoundingBoxType",
		"crs": "http://www.opengis.net/def/crs/EPSG/0/32631",
		"lowerCorner":
		[
			-9501965.72931276,
			-20003931.4586255
		],
		"upperCorner":
		[
			10501965.7293128,
			20003931.4586255
		]
	},
	"supportedCRS": "http://www.opengis.net/def/crs/EPSG/0/32631",
	"tileMatrix":
	[
		{
			"type": "TileMatrixType",
			"identifier": "1",
			"scaleDenominator": 279072704.500914,
			"topLeftCorner":
			[
				-9501965.72931276,
				20003931.4586255
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 1,
			"matrixHeight": 2
		},
		{
			"type": "TileMatrixType",
			"identifier": "2",
			"scaleDenominator": 139536352.250457,
			"topLeftCorner":
			[
				-9501965.72931276,
				20003931.4586255
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 2,
			"matrixHeight": 4
		},
		{
			"type": "TileMatrixType",
			"identifier": "3",
			"scaleDenominator": 69768176.1252285,
			"topLeftCorner":
			[
				-9501965.72931276,
				20003931.4586255
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 4,
			"matrixHeight": 8
		},
		{
			"type": "TileMatrixType",
			"identifier": "4",
			"scaleDenominator": 34884088.0626143,
			"topLeftCorner":
			[
				-9501965.72931276,
				20003931.4586255
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 8,
			"matrixHeight": 16
		},
		{
			"type": "TileMatrixType",
			"identifier": "5",
			"scaleDenominator": 17442044.0313071,
			"topLeftCorner":
			[
				-9501965.72931276,
				20003931.4586255
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 16,
			"matrixHeight": 32
		},
		{
			"type": "TileMatrixType",
			"identifier": "6",
			"scaleDenominator": 8721022.01565356,
			"topLeftCorner":
			[
				-9501965.72931276,
				20003931.4586255
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 32,
			"matrixHeight": 64
		},
		{
			"type": "TileMatrixType",
			"identifier": "7",
			"scaleDenominator": 4360511.00782678,
			"topLeftCorner":
			[
				-9501965.72931276,
				20003931.4586255
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 64,
			"matrixHeight": 128
		},
		{
			"type": "TileMatrixType",
			"identifier": "8",
			"scaleDenominator": 2180255.50391339,
			"topLeftCorner":
			[
				-9501965.72931276,
				20003931.4586255
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 128,
			"matrixHeight": 256
		},
		{
			"type": "TileMatrixType",
			"identifier": "9",
			"scaleDenominator": 1090127.7519567,
			"topLeftCorner":
			[
				-9501965.72931276,
				20003931.4586255
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 256,
			"matrixHeight": 512
		},
		{
			"type": "TileMatrixType",
			"identifier": "10",
			"scaleDenominator": 545063.875978348,
			"topLeftCorner":
			[
				-9501965.72931276,
				20003931.4586255
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 512,
			"matrixHeight": 1024
		},
		{
			"type": "TileMatrixType",
			"identifier": "11",
			"scaleDenominator": 272531.937989174,
			"topLeftCorner":
			[
				-9501965.72931276,
				20003931.4586255
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 1024,
			"matrixHeight": 2048
		},
		{
			"type": "TileMatrixType",
			"identifier": "12",
			"scaleDenominator": 136265.968994587,
			"topLeftCorner":
			[
				-9501965.72931276,
				20003931.4586255
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 2048,
			"matrixHeight": 4096
		},
		{
			"type": "TileMatrixType",
			"identifier": "13",
			"scaleDenominator": 68132.9844972935,
			"topLeftCorner":
			[
				-9501965.72931276,
				20003931.4586255
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 4096,
			"matrixHeight": 8192
		},
		{
			"type": "TileMatrixType",
			"identifier": "14",
			"scaleDenominator": 34066.4922486467,
			"topLeftCorner":
			[
				-9501965.72931276,
				20003931.4586255
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 8192,
			"matrixHeight": 16384
		},
		{
			"type": "TileMatrixType",
			"identifier": "15",
			"scaleDenominator": 17033.2461243234,
			"topLeftCorner":
			[
				-9501965.72931276,
				20003931.4586255
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 16384,
			"matrixHeight": 32768
		},
		{
			"type": "TileMatrixType",
			"identifier": "16",
			"scaleDenominator": 8516.62306216168,
			"topLeftCorner":
			[
				-9501965.72931276,
				20003931.4586255
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 32768,
			"matrixHeight": 65536
		},
		{
			"type": "TileMatrixType",
			"identifier": "17",
			"scaleDenominator": 4258.31153108084,
			"topLeftCorner":
			[
				-9501965.72931276,
				20003931.4586255
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 65536,
			"matrixHeight": 131072
		},
		{
			"type": "TileMatrixType",
			"identifier": "18",
			"scaleDenominator": 2129.15576554042,
			"topLeftCorner":
			[
				-9501965.72931276,
				20003931.4586255
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 131072,
			"matrixHeight": 262144
		},
		{
			"type": "TileMatrixType",
			"identifier": "19",
			"scaleDenominator": 1064.57788277021,
			"topLeftCorner":
			[
				-9501965.72931276,
				20003931.4586255
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 262144,
			"matrixHeight": 524288
		},
		{
			"type": "TileMatrixType",
			"identifier": "20",
			"scaleDenominator": 532.288941385105,
			"topLeftCorner":
			[
				-9501965.72931276,
				20003931.4586255
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 524288,
			"matrixHeight": 1048576
		},
		{
			"type": "TileMatrixType",
			"identifier": "21",
			"scaleDenominator": 266.144470692553,
			"topLeftCorner":
			[
				-9501965.72931276,
				20003931.4586255
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 1048576,
			"matrixHeight": 2097152
		},
		{
			"type": "TileMatrixType",
			"identifier": "22",
			"scaleDenominator": 133.072235346276,
			"topLeftCorner":
			[
				-9501965.72931276,
				20003931.4586255
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 2097152,
			"matrixHeight": 4194304
		},
		{
			"type": "TileMatrixType",
			"identifier": "23",
			"scaleDenominator": 66.5361176731382,
			"topLeftCorner":
			[
				-9501965.72931276,
				20003931.4586255
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 4194304,
			"matrixHeight": 8388608
		},
		{
			"type": "TileMatrixType",
			"identifier": "24",
			"scaleDenominator": 33.2680588365691,
			"topLeftCorner":
			[
				-9501965.72931276,
				20003931.4586255
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 8388608,
			"matrixHeight": 16777216
		}
	]
}

=== internetofwater/geoconnex.us/pygeoapi/schemas.opengis.net/tms/1.0/json/examples/WorldCRS84Quad.json
{
	"type": "TileMatrixSetType",
	"title": "CRS84 for the World",
	"identifier": "WorldCRS84Quad",
	"boundingBox":
	{
		"type": "BoundingBoxType",
		"crs": "http://www.opengis.net/def/crs/OGC/1.3/CRS84",
		"lowerCorner": [-180, -90],
		"upperCorner": [180, 90]
	},
	"supportedCRS": "http://www.opengis.net/def/crs/OGC/1.3/CRS84",
	"wellKnownScaleSet": "http://www.opengis.net/def/wkss/OGC/1.0/GoogleCRS84Quad",
	"tileMatrix":
	[
		{
			"type": "TileMatrixType",
			"identifier": "0",
			"scaleDenominator": 279541132.014358,
			"topLeftCorner": [-180, 90],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 2,
			"matrixHeight": 1
		},
		{
			"type": "TileMatrixType",
			"identifier": "1",
			"scaleDenominator": 139770566.007179,
			"topLeftCorner": [-180, 90],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 4,
			"matrixHeight": 2
		},
		{
			"type": "TileMatrixType",
			"identifier": "2",
			"scaleDenominator": 69885283.0035897,
			"topLeftCorner": [-180, 90],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 8,
			"matrixHeight": 4
		},
		{
			"type": "TileMatrixType",
			"identifier": "3",
			"scaleDenominator": 34942641.5017948,
			"topLeftCorner": [-180, 90],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 16,
			"matrixHeight": 8
		},
		{
			"type": "TileMatrixType",
			"identifier": "4",
			"scaleDenominator": 17471320.7508974,
			"topLeftCorner": [-180, 90],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 32,
			"matrixHeight": 16
		},
		{
			"type": "TileMatrixType",
			"identifier": "5",
			"scaleDenominator": 8735660.37544871,
			"topLeftCorner": [-180, 90],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 64,
			"matrixHeight": 32
		},
		{
			"type": "TileMatrixType",
			"identifier": "6",
			"scaleDenominator": 4367830.18772435,
			"topLeftCorner": [-180, 90],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 128,
			"matrixHeight": 64
		},
		{
			"type": "TileMatrixType",
			"identifier": "7",
			"scaleDenominator": 2183915.09386217,
			"topLeftCorner": [-180, 90],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 256,
			"matrixHeight": 128
		},
		{
			"type": "TileMatrixType",
			"identifier": "8",
			"scaleDenominator": 1091957.54693108,
			"topLeftCorner": [-180, 90],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 512,
			"matrixHeight": 256
		},
		{
			"type": "TileMatrixType",
			"identifier": "9",
			"scaleDenominator": 545978.773465544,
			"topLeftCorner": [-180, 90],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 1024,
			"matrixHeight": 512
		},
		{
			"type": "TileMatrixType",
			"identifier": "10",
			"scaleDenominator": 272989.386732772,
			"topLeftCorner": [-180, 90],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 2048,
			"matrixHeight": 1024
		},
		{
			"type": "TileMatrixType",
			"identifier": "11",
			"scaleDenominator": 136494.693366386,
			"topLeftCorner": [-180, 90],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 4096,
			"matrixHeight": 2048
		},
		{
			"type": "TileMatrixType",
			"identifier": "12",
			"scaleDenominator": 68247.346683193,
			"topLeftCorner": [-180, 90],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 8192,
			"matrixHeight": 4096
		},
		{
			"type": "TileMatrixType",
			"identifier": "13",
			"scaleDenominator": 34123.6733415964,
			"topLeftCorner": [-180, 90],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 16384,
			"matrixHeight": 8192
		},
		{
			"type": "TileMatrixType",
			"identifier": "14",
			"scaleDenominator": 17061.8366707982,
			"topLeftCorner": [-180, 90],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 32768,
			"matrixHeight": 16384
		},
		{
			"type": "TileMatrixType",
			"identifier": "15",
			"scaleDenominator": 8530.91833539913,
			"topLeftCorner": [-180, 90],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 65536,
			"matrixHeight": 32768
		},
		{
			"type": "TileMatrixType",
			"identifier": "16",
			"scaleDenominator": 4265.45916769956,
			"topLeftCorner": [-180, 90],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 131072,
			"matrixHeight": 65536
		},
		{
			"type": "TileMatrixType",
			"identifier": "17",
			"scaleDenominator": 2132.72958384978,
			"topLeftCorner": [-180, 90],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 262144,
			"matrixHeight": 131072
		}
	]	
}
