=== internetofwater/geoconnex.us/pygeoapi/schemas.opengis.net/tms/1.0/json/tms-schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "",
	"description": "",
	"type": "object",
	"required": ["type", "identifier", "supportedCRS", "tileMatrix"],
	"properties": {
		"type": {
			"description": "Type of the Tile Matrix Set",
			"enum": ["TileMatrixSetType"]
		},
		"title": {
			"description": "Title of this tile matrix set, normally used for display to a human",
			"type": "string"
		},
		"abstract": {
			"description": "Brief narrative description of this tile matrix set, normally available for display to a human",
			"type": "string"
		},
		"keywords": {
			"description": "Unordered list of one or more commonly used or formalized word(s) or phrase(s) used to describe this dataset",
			"$ref": "#/definitions/keywords" 
		},
		"identifier": {
			"description": "Tile matrix set identifier",
			"type": "string"
		},
		"boundingBox":
		{
			"description": "Minimum bounding rectangle surrounding the tile matrix set, in the supported CRS",
			"$ref": "#/definitions/boundingBox" 
		},
		"supportedCRS": {
			"description": "Reference to one coordinate reference system (CRS)",
			"type": "string",
			"format": "uri"
		},
		"wellKnownScaleSet": {
			"description": "Reference to a well-known scale set",
			"type": "string",
			"format": "uri"
		},
		"tileMatrix":
		{
			"description": "Describes a scale level and its tile matrix",
			"$ref": "#/definitions/tileMatrix" 
		}
	},
	"definitions":{ 
		"keywords": {
			"description": "Unordered list of one or more commonly used or formalised word(s) or phrase(s) used to describe this resource",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"boundingBox": {
			"description": "Minimum bounding rectangle surrounding the tile matrix set, in the supported CRS",
			"type": "object",
			"required": ["type", "lowerCorner", "upperCorner"],
			"properties": 
			{
				"type": {
					"description": "Type of the Bounding Bos",
					"enum": ["BoundingBoxType"]
				},
				"crs": {
					"description": "",
					"type": "string",
					"format": "uri"
				},
				"lowerCorner": {					
					"description": "",
					"type": "array",
					"items": {
						"type": "number",
						"minItems": 2,
						"maxItems": 2
					}
				},
				"upperCorner": {					
					"description": "",
					"type": "array",
					"items": {
						"type": "number",
						"minItems": 2,
						"maxItems": 2
					}
				}
			}
		},
		"tileMatrix": 
		{
			"description": "",
			"type": "array",
			"items": {
				"description": "",
				"type": "object",
				"required": ["type", "identifier", "scaleDenominator", "topLeftCorner", "tileWidth", "tileHeight", "matrixWidth", "matrixHeight"],
				"properties": 
				{
					"type": {
						"description": "Type of the Tile Matrix",
						"enum": ["TileMatrixType"]
					},
					"title": {
						"description": "Title of this tile matrix set, normally used for display to a human",
						"type": "string"
					},
					"abstract": {
						"description": "Brief narrative description of this tile matrix set, normally available for display to a human",
						"type": "string"
					},
					"keywords": {
						"description": "Unordered list of one or more commonly used or formalized word(s) or phrase(s) used to describe this dataset",
						"$ref": "#/definitions/keywords" 
					},
					"identifier": {
						"description": "Tile matrix identifier",
						"type": "string"
					},
					"scaleDenominator": {
						"description": "Scale denominator level of this tile matrix",
						"type": "number"
					},
					"topLeftCorner": {					
						"description": "Position in CRS coordinates of the top-left corner of this tile matrix",
						"type": "array",
						"items": {
							"type": "number",
							"minItems": 2,
							"maxItems": 2
						}
					},
					"tileWidth": {
						"description": "Width of each tile of this tile matrix in pixels",
						"type": "number",
						"minimum": 1,
						"multipleOf" : 1
					},
					"tileHeight": {
						"description": "Height of each tile of this tile matrix in pixels",
						"type": "number",
						"minimum": 1,
						"multipleOf" : 1
					},
					"matrixWidth": {
						"description": "Width of the matrix (number of tiles in width)",
						"type": "number",
						"minimum": 1,
						"multipleOf" : 1
					},
					"matrixHeight": {
						"description": "Height of the matrix (number of tiles in height)",
						"type": "number",
						"minimum": 1,
						"multipleOf" : 1
					},
					"variableMatrixWidth": {
						"description": "Describes the rows that has variable matix width",
						"$ref": "#/definitions/variableMatrixWidth" 
					}
				}
			}
		},
		"variableMatrixWidth": {
			"description": "List of data structures defining the tiles rows that was variable width",
			"type": "array",
			"items": {
				"description": "Variable Matrix Width data structure",
				"type": "object",
				"required": ["type", "coalesce", "minTileRow", "maxTileRow"],
				"properties": 
				{
					"type": {
						"description": "Type of the Variable Matrix Width",
						"enum": ["VariableMatrixWidthType"]
					},
					"coalesce" : {
						"description": "Coalescence factor",
						"type": "number",
						"minimum": 2,
						"multipleOf" : 1
					},
					"minTileRow": {
						"description": "Minimum tile row index valid for this layer",
						"type": "number",
						"minimum": 0,
						"multipleOf" : 1
					},
					"maxTileRow": {
						"description": "Maximim tile row index valid for this layer",
						"type": "number",
						"minimum": 0,
						"multipleOf" : 1
					}
				}
			}
		}
	}
}

=== internetofwater/geoconnex.us/pygeoapi/schemas.opengis.net/tms/1.0/json/examples/UPSAntarcticWGS84Quad.json
{
	"type": "TileMatrixSetType",
	"title": "AntarcticUniversalPolarStereoWGS84Quad",
	"identifier": "Universal Polar Stereographic WGS 84 Quad for Antarctic",
	"boundingBox":
	{
		"type": "BoundingBoxType",
		"crs": "http://www.opengis.net/def/crs/EPSG/0/5042",
		"lowerCorner":
		[
			-14440759.350252,
			-14440759.350252
		],
		"upperCorner":
		[
			18440759.350252,
			18440759.350252
		]
	},
	"supportedCRS": "http://www.opengis.net/def/crs/EPSG/0/5042",
	"tileMatrix":
	[
		{
			"type": "TileMatrixType",
			"identifier": "0",
			"scaleDenominator": 458726544.4,
			"topLeftCorner":
			[
				-14440759.350252,
				18440759.350252
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 1,
			"matrixHeight": 1
		},
		{
			"type": "TileMatrixType",
			"identifier": "1",
			"scaleDenominator": 229363272.2,
			"topLeftCorner":
			[
				-14440759.350252,
				18440759.350252
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 2,
			"matrixHeight": 2
		},
		{
			"type": "TileMatrixType",
			"identifier": "2",
			"scaleDenominator": 114681636.1,
			"topLeftCorner":
			[
				-14440759.350252,
				18440759.350252
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 4,
			"matrixHeight": 4
		},
		{
			"type": "TileMatrixType",
			"identifier": "3",
			"scaleDenominator": 57340818.05,
			"topLeftCorner":
			[
				-14440759.350252,
				18440759.350252
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 8,
			"matrixHeight": 8
		},
		{
			"type": "TileMatrixType",
			"identifier": "4",
			"scaleDenominator": 28670409.02,
			"topLeftCorner":
			[
				-14440759.350252,
				18440759.350252
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 16,
			"matrixHeight": 16
		},
		{
			"type": "TileMatrixType",
			"identifier": "5",
			"scaleDenominator": 14335204.51,
			"topLeftCorner":
			[
				-14440759.350252,
				18440759.350252
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 32,
			"matrixHeight": 32
		},
		{
			"type": "TileMatrixType",
			"identifier": "6",
			"scaleDenominator": 7167602.256,
			"topLeftCorner":
			[
				-14440759.350252,
				18440759.350252
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 64,
			"matrixHeight": 64
		},
		{
			"type": "TileMatrixType",
			"identifier": "7",
			"scaleDenominator": 3583801.128,
			"topLeftCorner":
			[
				-14440759.350252,
				18440759.350252
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 128,
			"matrixHeight": 128
		},
		{
			"type": "TileMatrixType",
			"identifier": "8",
			"scaleDenominator": 1791900.564,
			"topLeftCorner":
			[
				-14440759.350252,
				18440759.350252
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 256,
			"matrixHeight": 256
		},
		{
			"type": "TileMatrixType",
			"identifier": "9",
			"scaleDenominator": 895950.282,
			"topLeftCorner":
			[
				-14440759.350252,
				18440759.350252
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 512,
			"matrixHeight": 512
		},
		{
			"type": "TileMatrixType",
			"identifier": "10",
			"scaleDenominator": 447975.141,
			"topLeftCorner":
			[
				-14440759.350252,
				18440759.350252
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 1024,
			"matrixHeight": 1024
		},
		{
			"type": "TileMatrixType",
			"identifier": "11",
			"scaleDenominator": 223987.5705,
			"topLeftCorner":
			[
				-14440759.350252,
				18440759.350252
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 2048,
			"matrixHeight": 2048
		},
		{
			"type": "TileMatrixType",
			"identifier": "12",
			"scaleDenominator": 111993.7852,
			"topLeftCorner":
			[
				-14440759.350252,
				18440759.350252
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 4096,
			"matrixHeight": 4096
		},
		{
			"type": "TileMatrixType",
			"identifier": "13",
			"scaleDenominator": 55996.89262,
			"topLeftCorner":
			[
				-14440759.350252,
				18440759.350252
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 8192,
			"matrixHeight": 8192
		},
		{
			"type": "TileMatrixType",
			"identifier": "14",
			"scaleDenominator": 27998.44631,
			"topLeftCorner":
			[
				-14440759.350252,
				18440759.350252
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 16384,
			"matrixHeight": 16384
		},
		{
			"type": "TileMatrixType",
			"identifier": "15",
			"scaleDenominator": 13999.22316,
			"topLeftCorner":
			[
				-14440759.350252,
				18440759.350252
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 32768,
			"matrixHeight": 32768
		},
		{
			"type": "TileMatrixType",
			"identifier": "16",
			"scaleDenominator": 6999.611578,
			"topLeftCorner":
			[
				-14440759.350252,
				18440759.350252
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 65536,
			"matrixHeight": 65536
		},
		{
			"type": "TileMatrixType",
			"identifier": "17",
			"scaleDenominator": 3499.805789,
			"topLeftCorner":
			[
				-14440759.350252,
				18440759.350252
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 131072,
			"matrixHeight": 131072
		},
		{
			"type": "TileMatrixType",
			"identifier": "18",
			"scaleDenominator": 1749.902894,
			"topLeftCorner":
			[
				-14440759.350252,
				18440759.350252
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 262144,
			"matrixHeight": 262144
		},
		{
			"type": "TileMatrixType",
			"identifier": "19",
			"scaleDenominator": 874.9514472,
			"topLeftCorner":
			[
				-14440759.350252,
				18440759.350252
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 524288,
			"matrixHeight": 524288
		},
		{
			"type": "TileMatrixType",
			"identifier": "20",
			"scaleDenominator": 437.4757236,
			"topLeftCorner":
			[
				-14440759.350252,
				18440759.350252
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 1048576,
			"matrixHeight": 1048576
		},
		{
			"type": "TileMatrixType",
			"identifier": "21",
			"scaleDenominator": 218.7378618,
			"topLeftCorner":
			[
				-14440759.350252,
				18440759.350252
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 2097152,
			"matrixHeight": 2097152
		},
		{
			"type": "TileMatrixType",
			"identifier": "22",
			"scaleDenominator": 109.3689309,
			"topLeftCorner":
			[
				-14440759.350252,
				18440759.350252
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 4194304,
			"matrixHeight": 4194304
		},
		{
			"type": "TileMatrixType",
			"identifier": "23",
			"scaleDenominator": 54.68446545,
			"topLeftCorner":
			[
				-14440759.350252,
				18440759.350252
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 8388608,
			"matrixHeight": 8388608
		},
		{
			"type": "TileMatrixType",
			"identifier": "24",
			"scaleDenominator": 27.34223273,
			"topLeftCorner":
			[
				-14440759.350252,
				18440759.350252
			],
			"tileWidth": 256,
			"tileHeight": 256,
			"matrixWidth": 16777216,
			"matrixHeight": 16777216
		}
	]
}
